spring:
  application:
    name: orchidbe

  profiles:
    active: test

  data:
    mongodb:
      uri: mongodb://localhost:27017/orchid_db

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

server:
  port: 8080

api:
  prefix: /api/v1

jwt:
  expiration: 86400
  expiration-refresh-token: 5184000
  secretKey: NguyenHoangDucMinhNguyenHoangDucMinhNguyenHoangDucMinh