spring:
  application:
    name: orchidbe

  profiles:
    active: test

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=orchild;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

server:
  port: 8080

api:
  prefix: /api/v1

jwt:
  expiration: 86400
  expiration-refresh-token: 5184000
  secretKey: NguyenHoangDucMinhNguyenHoangDucMinhNguyenHoangDucMinh